[tool.poetry]
name = "pymetalink"
version = "0"
description = "A metalink library for Python"
authors = ["Neil McNab <nabber00@gmail.com>", "Bram Neijt <bram@neijt.nl>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "metalink" }]
repository = "https://github.com/metalink-dev/pymetalink"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
black = "^24.4.2"

[tool.poetry.scripts]
pymetalink = 'metalink.console:main'

[tool.poetry-version-plugin]
source = "git-tag"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
