name: pymetalink Testing Suite

on:
  push:
    branches: [$default-branch]
  pull_request:

jobs:
  main:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          python -m pip install poetry==1.8.3
      - name: Install pymetalink
        run: |
          python -m poetry install
      - name: Run linting
        if: matrix.python-version == '3.8'
        run: |
          python -m poetry run black --check .
      - name: Run tests
        run: |
          python -m poetry run pytest tests/test_metalink4.py
