name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - run: pip install poetry==1.9.0
      - run: |
          poetry install
      - name: Build and Publish
        env:
          POETRY_HTTP_BASIC_FOO_USERNAME: ${{ secrets.PYPI_USERNAME }}
          POETRY_HTTP_BASIC_FOO_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry self add poetry-version-plugin
          poetry build
          poetry publish
