name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install poetry and poetry-version-plugin
        run: |
          python -m pip install poetry==1.8.3
          python -m poetry self add poetry-version-plugin==0.2.0
      - name: Install pymetalink
        run: |
          python -m poetry install
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m poetry version ${{ github.event.release.tag_name }}
          python -m poetry build
          python -m poetry run twine upload dist/*
